services:
  spot-bot:
    build: .
    container_name: spot-bot
    restart: always
    # Читаем ключи из файла .env
    env_file:
      - .env
    environment:
      # Можно переопределить настройки тут, если нужно
      - LOG_LEVEL=INFO
    volumes:
      - .:/app
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    networks:
      - spot-bot-net

networks:
  spot-bot-net:
    driver: bridge
